; THIS ASSEMBLY CODE COMPUTES THE SUM OF DOUBLE WORD SIZED ELEMENTS OF ARRAY OF LENGTH TEN

DATA SEGMENT                         	; A SEGMENT NAMED AS DATA
 
    ARRAY   DD 3022546H , 1243H , 23456789H , 12345H , 342876H , 66798123H , D5432H , 62H , 421FH , 4682H  
    ; INITIALIZING THE ELEMENT OF ARRAY
    SUM     DD 0H                    	; TO STORE THE SUM OF ARRAY ELEMENT

DATA ENDS                            	; END OF DATA SEGMENT

CODE SEGMENT                         	; A SEGMENT NAMED AS CODE
    
    ASSUME DS:DATA,CS:CODE        
    ; INFORM THE ASSEMBLER THAT DATA SEGMENT IS ASSOCIATED WITH DS AND CODE SEGMENT IS ASSOCIATED WITH CS

    START:                           	; MAIN OF PROGRAM
    
            MOV AX , DATA
            MOV DS , AX                 ; LOADS DS WITH THE ADDRESS OF DATA SEGMENT
            
            XOR AX , AX
            MOV SI , 0H
            LEA BX , ARRAY              ; LOADS EFFECTIVE ADDRESS OF ARRAY TO BX REGISTER

	    ADD AX , WORD PTR BX[SI]    ; ADD LOWER 16 BIT OF FIRST DOUBLE WORD ELEMENT TO AX
      	    MOV WORD PTR SUM , AX     	; MOVE THE CONTENT OF AX REGISTER TO LOWER 16 BIT OF SUM
            MOV AX , 0H			; CLEARING AX
            ADD AX , WORD PTR BX[SI+2]	; ADD LOWER 16 BIT OF FIRST DOUBLE WORD ELEMENT TO AX
            MOV WORD PTR SUM+2 , AX	; MOVE THE CONTENT OF AX REGISTER TO UPPER 16 BIT OF SUM
 

            MOV CX , 09H                ; CX IS INTIALIZED WITH 9 TO EXECUTE LOOP 9 TIMES
            
    NEXT:  
	    INC SI
            INC SI
            INC SI                      ; INCREMENT SI BY 4 TO MOVE TO THE NEXT ELEMENT OF THE ARRAY
            INC SI

            MOV AX , WORD PTR SUM      	; MOVE LOWER 16 BITS OF SUM TO AX   
            ADC AX , WORD PTR BX[SI]   	; ADD LOWER 16 BITS OF ARRAY ELEMENTS WITH AX
            MOV WORD PTR SUM , AX       ; STORE CONTENT OF AX TO LOWER 16 BITS OF SUM 
            
            MOV AX , WORD PTR SUM+2     ; MOVE HIGHER 16 BITS OF SUM TO AX
            ADC AX , WORD PTR BX[SI+2]  ; ADD HIGHER 16 BITS OF ARRAY ELEMENTS WITH AX
            MOV WORD PTR SUM+2 , AX     ; STORE CONTENT OF AX TO LOWER 16 BITS OF SUM 

            LOOP NEXT                	; REPEAT UNTIL CX != 0H
 
CODE ENDS                            	; END OF CODE SEGMENT
    END START                        	; END OF PRORAM
