; THIS ASSEMBLY CODE MOVE A BLOCK OF DATA FROM ONE MEMORY LOCATION TO ANOTHER MEMORY LOCATION

DATA SEGMENT                        ; A SEGMENT NAMED AS DATA

    ARRAY1 DB 09H,4H,06H,03H,08H,26H; INITIALIZING THE ELEMENTS OF ARRAY1
    ARRAY2 DB 6DUP(0)               ; INITIALIZING THE ELEMENTS OF ARRAY2 BY 0

DATA ENDS                           ; END OF DATA SEGMENT

CODE SEGMENT                        ; A SEGMENT NAMED AS CODE

    ASSUME DS:DATA , CS:CODE  
    ; INFORM TO ASSEMBLER THAT DATA SEGMENT IS ASSOCIATED WITH DS AND CODE SEGMENT IS ASSOCIATED WITH CS
    
    START:                          ; MAIN OF THE PROGRAM
            MOV AX , DATA
            MOV DS , AX             ; LOADS DS WITH THE ADDRESS OF DATA SEGMENT
            
            LEA BX , ARRAY1         ; LOADS EFFECTIVE ADDRESS OF ARRAY1 TO BX REGISTER
            LEA BP , ARRAY2         ; LOADS EFFECTIVE ADDRESS OF ARRAY2 TO BP REGISTER
            MOV CX , 06H            ; CX IS INTIALIZED WITH 6 TO EXECUTE LOOP 6 TIMES

    NEXT: 
            MOV AL , BX[SI]         ; MOVE THE CONTENT AVAILABLE AT LOCATION [BX + SI ] TO AL REGISTER
	        INC SI                  ; SI IS INCREMENTED BY 1

            MOV BP[DI] , AL         ; MOVE THE CONTENT OF AL TO LOCATION [ BP + DI ] 
            INC DI                  ; DI IS INCREMENTED BY 1

            LOOP NEXT               ; REPEAT UNTIL CX != 0H
          
 CODE ENDS                          ; END OF CODE SEGMENT
    END START                       ; END OF THE PROGRAM
