; THIS ASSEMBLY CODE MOVE A BLOCK OF DATA FROM ONE MEMORY LOCATION TO ANOTHER

DATA SEGMENT                        ; A SEGMENT NAMED AS DATA

    ARRAY1 DB 09H,04H,06H,03H,08H   ; INITIALIZING THE ELEMENTS OF ARRAY1
    ARRAY2 DB 5DUP(0)               ; INITIALIZING THE ELEMENTS OF ARRAY2 BY 0

DATA ENDS                           ; END OF DATA SEGMENT

CODE SEGMENT                        ; A SEGMENT NAMED AS CODE

    ASSUME DS:DATA , CS:CODE  
    ; INFORM TO ASSEMBLER THAT DATA SEGMENT IS ASSOCIATED WITH DS AND CODE SEGMENT IS ASSOCIATED WITH CS
    
    START:                          ; MAIN OF THE PROGRAM
            MOV AX , DATA
            MOV DS , AX             ; LOADS DS WITH THE ADDRESS OF DATA SEGMENT
            
            LEA BX , ARRAY1         ; LOADS EFFECTIVE ADDRESS OF ARRAY1 TO BX REGISTER
            LEA BP , ARRAY2         ; LOADS EFFECTIVE ADDRESS OF ARRAY2 TO BP REGISTER
            MOV CX , 05H            ; CX IS INTIALIZED WITH 5 TO EXECUTE LOOP 5 TIMES
    NEXT: 
            MOV AL , BX[SI]         ; MOVE THE CONTENT AVAILABLE AT LOCATION [BX + SI ] TO AL REGISTER
            MOV BP[DI] , AL         ; MOVE THE CONTENT OF AL TO LOCATION [ BP + DI ] 
            INC SI                  ; SI IS INCREMENTED BY 1
            INC DI                  ; DI IS INCREMENTED BY 1
            LOOP NEXT               ; REPEAT TILL CX = 0H
          
 CODE ENDS                          ; END OF CODE SEGMENT
    END START                       ; END OF PRORAM
